
apiVersion: v1beta1
kind: Fleet
metadata:
  name: my-fleet
spec:
  selector:
    matchLabels:
      fleet: my-fleet
  template:
    spec:
      os:
        image: quay.io/mbang1/centos-bootc-cncf:v1
      config:
        - name: motd-update
          inline:
            - path: "/etc/motd"
              content: "This system is managed by flightctl."
              mode: 0644
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
      applications:
        - name: nginx-server
          appType: quadlet
          runAs: flightctl
          inline:
            - path: nginx.container
              content: |
                [Unit]
                Description=Nginx web server

                [Container]
                Image=docker.io/nginx:1.29
                PublishPort=8080:80

                [Service]
                Restart=always

                [Install]
                WantedBy=default.target
                
